version: '2'
services:
  idp.tutorial.stack-dev.cirrusidentity.com:
    build: build
    volumes:
      - ./simplesamlphp:/code
      - ./idp:/conf
    working_dir: /code
    environment:
      - SIMPLESAMLPHP_CONFIG_DIR=/conf/
    links:
      - mysql

  proxy.tutorial.stack-dev.cirrusidentity.com:
    build: build
    volumes:
      - ./simplesamlphp:/code
      - ./proxy:/conf
    working_dir: /code
    environment:
      - SIMPLESAMLPHP_CONFIG_DIR=/conf/

  sp1.tutorial.stack-dev.cirrusidentity.com:
    build: build
    hostname: sp1
    volumes:
      - ./simplesamlphp:/code
      - ./sp1:/conf
    working_dir: /code
    environment:
      - SIMPLESAMLPHP_CONFIG_DIR=/conf/
    command: apache2 -D FOREGROUND
    links:
      - redis

  sp2.tutorial.stack-dev.cirrusidentity.com:
    build: build
    volumes:
      - ./simplesamlphp:/code
      - ./sp2:/conf
    working_dir: /code
    environment:
      - SIMPLESAMLPHP_CONFIG_DIR=/conf/
    links:
      - memcached

  memcached:
    image: memcached

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: sessions
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootpassword

  redis:
    image: redis

  gencert:
    image: cfssl/cfssl
    volumes:
      - .:/work
    working_dir: /work
    entrypoint: /bin/bash
    command:
      - ./ca/generate.sh

  nginx:
    image: nginx:stable
    links:
      - idp.tutorial.stack-dev.cirrusidentity.com
      - proxy.tutorial.stack-dev.cirrusidentity.com
      - sp1.tutorial.stack-dev.cirrusidentity.com
      - sp2.tutorial.stack-dev.cirrusidentity.com
    volumes:
      - ./nginx:/etc/nginx:ro
    ports:
      - '80:80'
      - '443:443'
